apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
  {{- include "multi-k8s.targetNamespace" . | nindent 2 }}
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
