apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  {{- include "multi-k8s.targetNamespace" . | nindent 2 }}
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000
