apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  {{- include "multi-k8s.targetNamespace" . | nindent 2 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: chenggang/multi-client
          ports:
            - containerPort: 3000
