apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.name }}
  {{- include "multi-k8s.targetNamespace" . | nindent 2 }}
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
