apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
  {{- include "multi-k8s.targetNamespace" . | nindent 2 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: chenggang/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
