# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Release Charts
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        # https://github.com/marketplace/actions/helm-tool-installer
        uses: azure/setup-helm@v1
        with:
          version: v3.6.0

      - name: run chart-releaser
        # https://github.com/marketplace/actions/helm-chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
